/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fea619",
        "inverse-on-surface": "#f1f1f0",
        "on-background": "#0f172a",
        "error-container": "#ffdad6",
        "tertiary-container": "#575250",
        "surface-container-high": "#e2e8f0",
        "on-secondary-container": "#684000",
        "on-secondary-fixed-variant": "#653e00",
        "surface-bright": "#f4f8ee",
        "on-error-container": "#93000a",
        "surface-tint": "#0d1c32",
        "on-primary-fixed": "#002116",
        "on-tertiary-fixed": "#1e1b19",
        "on-surface-variant": "#475569",
        "primary": "#0d1c32",
        "secondary": "#855300",
        "tertiary-fixed": "#e9e1dd",
        "surface": "#f4f8ee",
        "on-tertiary-container": "#cdc6c2",
        "tertiary": "#3f3b39",
        "surface-container-low": "#f4f8ee",
        "primary-fixed-dim": "#8bd6b7",
        "inverse-surface": "#1e293b",
        "outline-variant": "#cbd5e1",
        "inverse-primary": "#8bd6b7",
        "surface-variant": "#e2e8f0",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#4a4643",
        "surface-dim": "#cbd5e1",
        "error": "#ba1a1a",
        "primary-container": "#1e293b",
        "background": "#f4f8ee",
        "tertiary-fixed-dim": "#ccc5c2",
        "on-primary-fixed-variant": "#00513b",
        "on-primary-container": "#002116",
        "outline": "#64748b",
        "surface-container": "#eef3f0",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#2a1700",
        "primary-fixed": "#d1fae5",
        "on-surface": "#0f172a",
        "secondary-fixed": "#ffddb8",
        "surface-container-highest": "#cbd5e1"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "currency-display": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "currency-display": ["28px", { lineHeight: "32px", fontWeight: "700" }]
      },
      spacing: {
        "card-inner-padding": "20px",
        "tap-target-min": "48px",
        "stack-gap": "16px",
        "container-padding": "20px",
        "base": "4px"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
}
